apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-loki-grafana-go
  namespace: argocd
  labels:
    name: prometheus-loki-grafana-go
spec:
  project: default

  source:
    repoURL: https://github.com/vpapidokha/prometheus-loki-grafana-go-
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=false
    - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
