apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dragonfly-cluster
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dragonfly
    server: 'https://kubernetes.default.svc'
  source:
    path: dragonfly
    repoURL: 'https://github.com/vpapidokha/k8s-tools.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true